media:
  input: media/
  output: /media/

content:
  - name: performances
    label: Performance Archive
    type: collection
    path: _performances/
    extension: json        # Force the extension to be json
    format: json           # Force the data engine to save as a JSON object
    slug: "session-{{session_number}}"

    fields:
      - name: session_number
        label: Session Number
        type: number
        required: true

      - name: total_sessions
        label: Total Sessions
        type: number
        required: true

      - name: date
        label: Session Date
        type: date
        required: true

      - name: video_url
        label: Video URL / Link
        type: string
        required: true
